CREATE INDEX index_shop ON planet_osm_point (shop)
CREATE INDEX index_highway ON planet_osm_point (highway)
CREATE INDEX index_water ON planet_osm_point (water)
CREATE INDEX index_building ON planet_osm_point (building)
CREATE INDEX index_amenity ON planet_osm_point (amenity)